# Generated by Django 4.0 on 2021-12-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_userprofile_id_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_images/%d/%m/%Y/'),
        ),
    ]
