# Generated by Django 4.0 on 2021-12-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
