# Generated by Django 4.0 on 2021-12-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0007_userprofile_fr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fr',
        ),
    ]
