# Generated by Django 4.0 on 2021-12-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0008_remove_userprofile_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fr',
            field=models.CharField(default=0, max_length=100000),
            preserve_default=False,
        ),
    ]
