# Generated by Django 4.0 on 2021-12-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0009_userprofile_fr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
